### ISSUE TITLE
set_topic not working

### ISSUE THREAD

**Issue by pseidemann** [litaio/lita-slack#77]
hello,

I tried to use `robot.set_topic(response, 'some topic')` in my lita handler.
it seems that this method doesn't pass the room's id to the slack api but a string representation of the room object, so it misses `room.id` somewhere in the chain.

then I tried to use set_topic directly via `robot.chat_service.api.set_topic(response.room.id, 'some topic')` but still no luck. I always get `channel_not_found` error from slack. I checked the call made and it looks good to me (https://api.slack.com/methods/channels.setTopic). 
could it be that lita-slack somehow computes the wrong room id? there could be also something wrong with the api call to slack?

**Comment by pseidemann** [comment]
hi @jimmycuadra,
any chance this can be fixed? I don't know how to fix it myself

**Comment by pseidemann** [comment]
I found out that `robot.chat_service.api.set_topic(response.room.id, 'some topic')` seems to work with public channels but **not with private channels**.
`robot.set_topic(response, 'some topic')` doesn't work with either public nor private channels

**Comment by jimmycuadra** [comment]
Very sorry for leaving this issue sitting so long without a reply!

The first argument to `set_topic` should be a [Lita::Source](http://www.rubydoc.info/gems/lita/Lita/Robot#set_topic-instance_method) object, not a `Lita::Response`, so that is one problem that would keep the API from working for you. I am not sure about the distinction between public and private channels off hand. The bot will definitely need to be a member of any private channels it's trying to send a message to, but there may be an issue with how it's formatting IDs for private channels, too.

**Comment by pseidemann** [comment]
@jimmycuadra,
it seems like this works inside the handler at least for public channels:
```ruby
target = Source.new(room: response.room)
robot.set_topic(target, 'test')
``` 

thanks!
